export interface RuleCase {
	readonly name: string;
	readonly pass: string;
	readonly fail: string;
	readonly rules: readonly string[];
}

/** Fixtures are compiler-valid programs; only the intended lint boundary differs. */
export const ruleCases: readonly RuleCase[] = [
	{
		name: "explicit any includes rest arguments",
		pass: "export function value(...items: readonly unknown[]): unknown { return items[0]; }",
		fail: "export function value(...items: any[]): unknown { return items[0]; }",
		rules: ["typescript/no-explicit-any", "typescript/prefer-readonly-parameter-types"],
	},
	{
		name: "non-null assertions",
		pass: "export function value(input: string | undefined): string { return input ?? ''; }",
		fail: "export function value(input: string | undefined): string { return input!; }",
		rules: ["typescript/no-non-null-assertion"],
	},
	{
		name: "unsafe assertions cannot narrow unknown",
		pass: "export function value(input: unknown): string { return typeof input === 'string' ? input : ''; }",
		fail: "export function value(input: unknown): string { return input as string; }",
		rules: ["typescript/no-unsafe-type-assertion"],
	},
	{
		name: "unnecessary assertions include literal const assertions",
		pass: "export const value = 1;",
		fail: "export const value = 1 as const;",
		rules: ["typescript/no-unnecessary-type-assertion"],
	},
	{
		name: "object literal assertion style",
		pass: "export const value: { readonly count: number } = { count: 1 };",
		fail: "export const value = { count: 1 } as { readonly count: number };",
		rules: ["typescript/consistent-type-assertions"],
	},
	{
		name: "array literal assertion style",
		pass: "export const value: readonly number[] = [1];",
		fail: "export const value = [1] as readonly number[];",
		rules: ["typescript/consistent-type-assertions"],
	},
	{
		name: "unsafe JSON return",
		pass: "export function value(input: string): unknown { return JSON.parse(input); }",
		fail: "export function value(input: string): string { return JSON.parse(input); }",
		rules: ["typescript/no-unsafe-return"],
	},
	{
		name: "unsafe JSON assignment",
		pass: "export const value: unknown = JSON.parse('null');",
		fail: "export const value: string = JSON.parse('null');",
		rules: ["typescript/no-unsafe-assignment"],
	},
	{
		name: "unsafe JSON argument",
		pass: "export const value = Math.abs(1);",
		fail: "export const value = Math.abs(JSON.parse('1'));",
		rules: ["typescript/no-unsafe-argument"],
	},
	{
		name: "unsafe JSON call",
		pass: "export const value: unknown = JSON.parse('null');",
		fail: "export const value = JSON.parse('null')();",
		rules: ["typescript/no-unsafe-assignment", "typescript/no-unsafe-call"],
	},
	{
		name: "unsafe JSON member access",
		pass: "export const value: unknown = JSON.parse('null');",
		fail: "export const value: unknown = JSON.parse('null').name;",
		rules: ["typescript/no-unsafe-member-access"],
	},
	{
		name: "empty object types",
		pass: "export type Value = object;",
		fail: "export type Value = {};",
		rules: ["typescript/no-empty-object-type"],
	},
	{
		name: "unsafe Function types",
		pass: "export type Value = () => void;",
		fail: "export type Value = Function;",
		rules: ["typescript/no-unsafe-function-type"],
	},
	{
		name: "wrapper object types",
		pass: "export type Value = string;",
		fail: "export type Value = String;",
		rules: ["typescript/no-wrapper-object-types"],
	},
	{
		name: "void belongs to return and generic contracts",
		pass: "export type Value = () => void; export const value = Promise.resolve();",
		fail: "export const value: void = undefined;",
		rules: ["typescript/no-invalid-void-type"],
	},
	{
		name: "type parameters must relate inputs and outputs",
		pass: "export function value<T>(input: T): T { return input; }",
		fail: "export function value<T>(): T | undefined { return; }",
		rules: ["typescript/no-unnecessary-type-parameters"],
	},
	{
		name: "deprecated declarations",
		pass: "export function current(): number { return 1; } export const value = current();",
		fail: "/** @deprecated Use current instead. */\nexport function old(): number { return 1; }\nexport const value = old();",
		rules: ["typescript/no-deprecated"],
	},
	{
		name: "unbound methods preserve this ownership",
		pass: "export class Value { readonly count = 1; read(): number { return this.count; } } export const value = new Value().read.bind(new Value());",
		fail: "export class Value { readonly count = 1; read(): number { return this.count; } } export const value = new Value().read;",
		rules: ["typescript/unbound-method"],
	},
	{
		name: "spreading a Promise is not its result",
		pass: "export const value = { count: 1 };",
		fail: "export const value = { ...Promise.resolve(1) };",
		rules: ["typescript/no-misused-spread", "typescript/no-misused-promises"],
	},
	{
		name: "for-in arrays uses numeric keys accidentally",
		pass: "export function value(items: readonly string[]): string { let text = ''; for (const item of items) { text += item; } return text; }",
		fail: "export function value(items: readonly string[]): string { let text = ''; for (const item in items) { text += item; } return text; }",
		rules: ["typescript/no-for-in-array"],
	},
	{
		name: "numeric array sort requires comparison",
		pass: "export const value = [2, 1].sort((a, b) => a - b);",
		fail: "export const value = [2, 1].sort();",
		rules: ["typescript/require-array-sort-compare"],
	},
	{
		name: "primitive truthiness is explicit",
		pass: "export function value(input: string): boolean { return input.length > 0; }",
		fail: "export function value(input: string): boolean { if (input) { return true; } return false; }",
		rules: ["typescript/strict-boolean-expressions"],
	},
	{
		name: "nullable booleans cannot conflate false and absence",
		pass: "export function value(input: boolean | undefined): boolean { return input === true; }",
		fail: "export function value(input: boolean | undefined): boolean { if (input) { return true; } return false; }",
		rules: ["typescript/strict-boolean-expressions"],
	},
	{
		name: "nullable numbers cannot conflate zero and absence",
		pass: "export function value(input: number | undefined): boolean { return input !== undefined; }",
		fail: "export function value(input: number | undefined): boolean { if (input) { return true; } return false; }",
		rules: ["typescript/strict-boolean-expressions"],
	},
	{
		name: "nullable strings cannot conflate empty and absence",
		pass: "export function value(input: string | undefined): boolean { return input !== undefined; }",
		fail: "export function value(input: string | undefined): boolean { if (input) { return true; } return false; }",
		rules: ["typescript/strict-boolean-expressions"],
	},
	{
		name: "genuine constant conditions remain checked",
		pass: "export function value(input: boolean): number { if (input) { return 1; } return 0; }",
		fail: "export function value(): number { if (true) { return 1; } return 0; }",
		rules: ["typescript/no-unnecessary-condition", "eslint/no-constant-condition"],
	},
	{
		name: "default does not make a union exhaustive",
		pass: "export function value(input: 'a' | 'b'): number { switch (input) { case 'a': return 1; case 'b': return 2; } }",
		fail: "export function value(input: 'a' | 'b'): number { switch (input) { case 'a': return 1; default: return 2; } }",
		rules: ["typescript/switch-exhaustiveness-check"],
	},
	{
		name: "strict equality",
		pass: "export function value(input: number): boolean { return input === 1; }",
		fail: "export function value(input: number): boolean { return input == 1; }",
		rules: ["eslint/eqeqeq"],
	},
	{
		name: "implicit coercion",
		pass: "export function value(input: number): boolean { return input !== 0; }",
		fail: "export function value(input: number): boolean { return !!input; }",
		rules: ["eslint/no-implicit-coercion", "typescript/strict-boolean-expressions"],
	},
	{
		name: "mixed plus operands",
		pass: "export function value(input: number): string { return String(input) + ' items'; }",
		fail: "export function value(input: number): string { return input + ' items'; }",
		rules: ["typescript/restrict-plus-operands"],
	},
	{
		name: "template arrays are not scalar text",
		pass: "export function value(input: readonly number[]): string { return `items: ${input.join(',')}`; }",
		fail: "export function value(input: readonly number[]): string { return `${input}`; }",
		rules: ["typescript/restrict-template-expressions"],
	},
	{
		name: "unknown cannot stringify as a base object",
		pass: "export function value(input: unknown): string { return typeof input === 'string' ? input : 'unknown'; }",
		fail: "export function value(input: unknown): string { return String(input); }",
		rules: ["typescript/no-base-to-string"],
	},
	{
		name: "floating native promises remain errors",
		pass: "export async function value(): Promise<number> { return Promise.resolve(1); }",
		fail: "export function value(): void { Promise.resolve(1); }",
		rules: ["typescript/no-floating-promises", "promise/catch-or-return"],
	},
	{
		name: "void cannot waive floating ownership",
		pass: "export async function value(): Promise<void> { await Promise.resolve(); }",
		fail: "export function value(): void { void Promise.resolve(); }",
		rules: ["typescript/no-floating-promises"],
	},
	{
		name: "misused Promise callbacks",
		pass: "export async function value(): Promise<void> { await Promise.all([1].map(async () => Promise.resolve())); }",
		fail: "export function value(): void { [1].forEach(async () => Promise.resolve()); }",
		rules: ["typescript/no-misused-promises", "typescript/strict-void-return"],
	},
	{
		name: "await only thenables",
		pass: "export async function value(): Promise<number> { return await Promise.resolve(1); }",
		fail: "export async function value(): Promise<number> { return await 1; }",
		rules: [
			"typescript/await-thenable",
			"typescript/return-await",
			"unicorn/no-unnecessary-await",
		],
	},
	{
		name: "return-await within catch boundaries",
		pass: "export async function value(): Promise<number> { try { return await Promise.resolve(1); } catch { return 0; } }",
		fail: "export async function value(): Promise<number> { try { return Promise.resolve(1); } catch { return 0; } }",
		rules: ["typescript/return-await"],
	},
	{
		name: "void callbacks cannot discard nonvoid implicitly",
		pass: "export const value: () => void = () => { Math.abs(1); };",
		fail: "export const value: () => void = () => Math.abs(1);",
		rules: ["typescript/strict-void-return"],
	},
	{
		name: "void-return expression is not a value",
		pass: "export function value(): void { console.log('done'); }",
		fail: "export function value(): void { return console.log('done'); }",
		rules: ["typescript/no-confusing-void-expression"],
	},
	{
		name: "meaningless void",
		pass: "export function value(): void { console.log('done'); }",
		fail: "export function value(): void { void console.log('done'); }",
		rules: [
			"typescript/no-meaningless-void-operator",
			"typescript/no-confusing-void-expression",
		],
	},
	{
		name: "newly thrown failures are Errors",
		pass: "export function value(): never { throw new Error('failed'); }",
		fail: "export function value(): never { throw 'failed'; }",
		rules: ["typescript/only-throw-error"],
	},
	{
		name: "catch callback failure is unknown",
		pass: "export async function value(): Promise<void> { await Promise.reject(new Error('failed')).catch((error: unknown) => { console.log(error); }); }",
		fail: "export async function value(): Promise<void> { await Promise.reject(new Error('failed')).catch((error) => { console.log(error); }); }",
		rules: ["typescript/use-unknown-in-catch-callback-variable"],
	},
	{
		name: "Promise rejection requires Error",
		pass: "export async function value(): Promise<void> { await Promise.reject(new Error('failed')); }",
		fail: "export async function value(): Promise<void> { await Promise.reject('failed'); }",
		rules: ["typescript/prefer-promise-reject-errors"],
	},
	{
		name: "empty rejection is forbidden",
		pass: "export async function value(): Promise<void> { await Promise.reject(new Error('failed')); }",
		fail: "export async function value(): Promise<void> { await Promise.reject(); }",
		rules: ["typescript/prefer-promise-reject-errors"],
	},
	{
		name: "parameter properties cannot mutate shared state",
		pass: "export function value(input: { readonly count: number }): number { return input.count + 1; }",
		fail: "export function value(input: { count: number }): number { input.count = 1; return input.count; }",
		rules: ["eslint/no-param-reassign", "typescript/prefer-readonly-parameter-types"],
	},
	{
		name: "private fields written only at construction are readonly",
		pass: "export class Value { private readonly count = 1; read(): number { return this.count; } }",
		fail: "export class Value { private count = 1; read(): number { return this.count; } }",
		rules: ["typescript/prefer-readonly"],
	},
	{
		name: "public boundaries need explicit returns",
		pass: "export function value(input: number): number { return input; }",
		fail: "export function value(input: number) { return input; }",
		rules: ["typescript/explicit-module-boundary-types"],
	},
	{
		name: "application interface methods are readonly properties",
		pass: "export interface Value { readonly read: () => number; }",
		fail: "export interface Value { read(): number; }",
		rules: ["typescript/method-signature-style"],
	},
	{
		name: "imports cannot be side-effect-only after type removal",
		pass: "import type { Stats } from 'node:fs'; export type Value = Stats;",
		fail: "import { type Stats } from 'node:fs'; export type Value = Stats;",
		rules: ["typescript/no-import-type-side-effects"],
	},
	{
		name: "mutable exports",
		pass: "export const value = 1;",
		fail: "export let value = 1;",
		rules: ["import/no-mutable-exports", "eslint/prefer-const"],
	},
	{
		name: "curly control flow",
		pass: "export function value(input: boolean): number { if (input) { return 1; } return 0; }",
		fail: "export function value(input: boolean): number { if (input) return 1; return 0; }",
		rules: ["eslint/curly"],
	},
	{
		name: "var declarations",
		pass: "export function value(): number { const count = 1; return count; }",
		fail: "export function value(): number { var count = 1; return count; }",
		rules: ["eslint/no-var"],
	},
	{
		name: "prefer immutable local bindings",
		pass: "export function value(): number { const count = 1; return count; }",
		fail: "export function value(): number { let count = 1; return count; }",
		rules: ["eslint/prefer-const"],
	},
	{
		name: "nested ternaries",
		pass: "export function value(a: boolean, b: boolean): number { if (a) { return 1; } return b ? 2 : 3; }",
		fail: "export function value(a: boolean, b: boolean): number { return a ? 1 : b ? 2 : 3; }",
		rules: ["eslint/no-nested-ternary"],
	},
	{
		name: "return assignment",
		pass: "export function value(): number { let count = 0; count += 1; return count; }",
		fail: "export function value(): number { let count = 0; console.log(count); return (count = 1); }",
		rules: ["eslint/no-return-assign"],
	},
	{
		name: "sequence expressions",
		pass: "export function value(): number { console.log('done'); return 1; }",
		fail: "export function value(): number { let count = 0; count++, console.log('done'); return count; }",
		rules: [
			"eslint/no-sequences",
			"eslint/no-unused-expressions",
			"typescript/no-confusing-void-expression",
		],
	},
	{
		name: "multiple assignment",
		pass: "export function value(): number { let a = 0; let b = 0; a = 1; b = 1; return a + b; }",
		fail: "export function value(): number { let a = 0; let b = 0; a = b = 1; return a + b; }",
		rules: ["eslint/no-multi-assign"],
	},
	{
		name: "else after returning",
		pass: "export function value(input: boolean): number { if (input) { return 1; } return 0; }",
		fail: "export function value(input: boolean): number { if (input) { return 1; } else { return 0; } }",
		rules: ["eslint/no-else-return"],
	},
	{
		name: "debugger statements",
		pass: "export function value(): void { console.log('done'); }",
		fail: "export function value(): void { debugger; }",
		rules: ["eslint/no-debugger"],
	},
	{
		name: "unexpected control-character regex",
		pass: "export const value = /[a-z]/u;",
		fail: "export const value = /[\\u0000-\\u001F]/u;",
		rules: ["eslint/no-control-regex"],
	},
	{
		name: "empty catches do not swallow failure",
		pass: "export function value(): number { try { return Number('1'); } catch { return 0; } }",
		fail: "export function value(): number { try { return Number('1'); } catch {} return 0; }",
		rules: ["eslint/no-empty"],
	},
	{
		name: "no-op functions need explanations",
		pass: "export function value(): void { /* This sink owns no resources to flush. */ }",
		fail: "export function value(): void {}",
		rules: ["eslint/no-empty-function"],
	},
	{
		name: "unnecessary explicit undefined",
		pass: "export const value: () => undefined = () => { return; };",
		fail: "export const value: () => undefined = () => undefined;",
		rules: ["unicorn/no-useless-undefined"],
	},
];
